### ISSUE TITLE
Question on Updated Data for US

### ISSUE THREAD

**Issue by rylanb** [midwire/free_zipcode_data#2]
### Expected Behavior
80108 / 80109 zipcodes exist in the all_us_zipcodes.csv file and can be updated via https://github.com/midwire/my_zipcode_gem scripts.

### Actual Behavior
80108 / 80109 and other zipcodes (likely) do exist and can populate / keep data up-to-date for production systems.

There is -> `80104,Castle Rock,CO,DOUGLAS,,39.374779,-104.849988` in the data, which is great, but there are more zip codes that represent Castle Rock, CO.

### Steps to reproduce the problem

Go to https://raw.githubusercontent.com/midwire/free_zipcode_data/master/all_us_zipcodes.csv
and search for 80108 and/or 80109 and notice that Castle Rock, CO is not in that CSV file.

If you download the data from Geonames, those are in the `US.txt` file in the `US.zip`.

I'm more than happy to work on this gem and the my_zipcode_gem to help keep things up-to-date but I find it confusing that the all_us_zipcodes.csv is generated from the my_zipcode_gem and is now 3 months out of date. What's the process for running that properly with new data and updating?

Thanks for your work on this gem, it has gotten us very far on our production application!

---
* Current Version: Cloned direct from master
* Operating System: Mac OS X 10.11.6

**Comment by rylanb** [comment]
As an addendum to this that is slightly related: 

When I tried to grab the data and create my own CSV I had errors around County names in the `US.txt` file: 

`Aleutians West (CA)` and `Anchorage Municipality` for importing with the https://github.com/midwire/my_zipcode_gem/blob/master/lib/generators/my_zipcode_gem/templates/zipcodes.rake rake task.

Does the my_zipcode_gem sanitize those somehow that I'm missing? 

Thanks again!

**Comment by cmckni3** [comment]
I can look into it when I can. At ng-conf this week though.

**Comment by rylanb** [comment]
@midwire No big deal! 

I'd be happy to try and help out. I do already do some OSS maintaining. Please do include me when you start looking at a refactor or re-write! Love to try and work it in, if I can!

**Comment by midwire** [comment]
FYI: This is related to Issue #4 and will be resolved as part of our ongoing refactor.
