### ISSUE TITLE
Incorrect Zip Codes to County data mapping

### ISSUE THREAD

**Issue by MOZGIII** [midwire/free_zipcode_data#3]
### Expected Behavior

85602 zip code to have two counties.

```csv
85602,Benson,AZ,COCHISE,,32.035885,-110.262611
85602,Benson,AZ,PIMA,,...,...
```

There's no surjection between the set of zip codes and set of counties.

A somewhat helpful explanation of this fact in reality by census bureau:
[explanation_zcta_county_rel_10.pdf](https://github.com/midwire/free_zipcode_data/files/1694209/explanation_zcta_county_rel_10.pdf)

The problem is generic, not just this zip code is affected. As I said, there's no surjection between the set of zip codes and set of counties in general.

### Actual Behavior

85602 only has a single county: AZ, COCHISE.

```csv
85602,Benson,AZ,COCHISE,,32.035885,-110.262611
```

### Steps to reproduce the problem

1. Look into the data.
2. Look at here: https://www2.census.gov/geo/pdfs/maps-data/data/rel/explanation_zcta_county_rel_10.pdf

---
* Current Version: git @ 6599105
* Operating System: not relevant

**Comment by midwire** [comment]
@MOZGIII thanks for reporting this. We are considering a refactor and plan to disconnect this relationship.

**Comment by midwire** [comment]
Latest version 1.0.2 should resolve this issue. Please re-open if additional problems.
